@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.plantnetapp.back.api.ExternalBDDApi",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1228495093 { 
   	label=plantnetapp
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ExternalBDDApi2079699613[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ExternalBDDApi</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   URL_NAME: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addNumberWithoutDecimal(obj: JsonObject, key: String, value: float)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPlant(collectionID: String, plant: Plant, imageFile: File): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPlantCollection(userID: String, collectionName: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPlantCollectionWithID(userID: String, col: PlantCollection): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPlantWithoutCollection(userID: String, plant: Plant, imageFile: File): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ addUser(user: User): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ addUserWithID(user: User): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ checkStatus(): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ createInstance(): ExternalBDDApi</TD></TR>
<TR><TD ALIGN="LEFT" >+ deletePlant(collectionID: String, plantName: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ deletePlantCollection(userID: String, collectionName: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteUser(id: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllPlantCollections(userID: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllPlants(collectionID: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPlant(collectionID: String, plantName: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPlantCollection(userID: String, collectionName: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ linkImageToRequest(connection: HttpURLConnection, boundary: String, body: JsonObject, file: File, fileFieldName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ login(username: String, pswrd: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ sendDeleteRequest(endpoint: String, body: JsonObject): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ sendGetRequest(endpoint: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ sendHeadRequest(endpoint: String): ReturnType</TD></TR>
<TR><TD ALIGN="LEFT" >+ sendPostRequest(endpoint: String, body: JsonObject, file: File): ReturnType</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    

    
}
@enduml